### ISSUE TITLE
Cannot handle alternative RSS tag locations for magnet or torrent links

### ISSUE THREAD

**Issue by scriptzteam** [archangelic/torrentcatcher#3] opened 2016-03-22 13:02 UTC
tried with kat.cr but not works o.o

**Comment by archangelic** [comment] 2016-03-22 13:30
What was the command that you used? Was it a magnet link or was it a direct torrent link or was it (as intended) a link to an RSS feed?

**Comment by scriptzteam** [comment] 2016-03-22 17:42
kat.cr with https, rss link

**Comment by archangelic** [comment] 2016-03-22 18:10
Do you mind sharing the link to the feed? I think I made some assumptions of where in the feed the magnet link will be.

**Comment by archangelic** [comment] 2016-03-24 03:55
So, I think the issue is not with https, it is with the script not knowing which RSS tag contains the torrent or magnet link. Try cloning the dev branch:
[https://github.com/archangelic/torrentcatcher/tree/dev](url)

Let me know if that works. I will do more testing and close this issue once I merge to master.

**Closed as completed** 2016-03-27 09:12 UTC
Labels: bug

**Comment by archangelic** [comment] 2016-03-27 09:17
All changes pushed to pypi. Now when you run the script again, if you have an existing database, it will ask you to update your feeds by providing the rss tag where the magnet link is located. Once that is done, you should be fine. But when adding feeds, you will need to also include the magnet or torrent link tag.

Todo: Eventually I would like the script to detect if the feed has torrent or magnet links and get the tag automatically.
